local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

-- harpoon remaps
vim.keymap.set("n", "<C-a>", function ()
   mark.add_file()
   print("👉 file added to harpoon")
end)
vim.keymap.set("n", "<leader>fm", ui.toggle_quick_menu)

vim.keymap.set("n", "<C-h>", function()
    ui.nav_file(1)
end)
vim.keymap.set("n", "<C-j>", function()
    ui.nav_file(2)
end)
vim.keymap.set("n", "<C-k>", function()
    ui.nav_file(3)
end)
vim.keymap.set("n", "<C-l>", function()
    ui.nav_file(4)
end)
